language: php
dist: xenial
os: linux

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - pecl install igbinary
  - pecl install msgpack
  - composer update -o --no-interaction --prefer-source
  - wget https://scrutinizer-ci.com/ocular.phar

before_script:
  - phpenv config-rm xdebug.ini

script:
  - vendor/bin/phpunit --coverage-clover build/coverage/clover.xml

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage/clover.xml

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
