language: php
sudo: false
php:
  - 7.0
  - 7.1

before_script:
  - composer install -o --dev --no-interaction
script:
  - mkdir -p build/logs
  - phpunit
after_success:
  - travis_retry php vendor/bin/coveralls
