on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  timezone: UTC

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.0', '8.1']

    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: composer:v2, pecl
        coverage: pcov
        extensions: ctype dom igbinary libxml mbstring msgpack simplexml xml zip
        ini-values: assert.exception=1
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      run: composer update -o --prefer-dist --no-progress --no-interaction
    - name: test with phpunit
      run: vendor/bin/phpunit --verbose --coverage-text
